name: RDP-VPS

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok & NSSM

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe  -OutFile ngrok.exe

        Invoke-WebRequest https://drive.google.com/uc?id=1jE2e6JdVkkbqfavoLAJcOozctoKqrGV4  -OutFile nssm.exe

    - name: Copy NSSM & Ngrok to Windows Directory.

      run: | 

        copy nssm.exe C:\Windows\System32

        copy ngrok.exe C:\Windows\System32

    - name: Connect your NGROK account

      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Download Important Files.

      run: |

        Invoke-WebRequest https://drive.google.com/uc?id=1JChJjDtSKMkd0LfCjW5ovo2gwjPB16IW  -OutFile NGROK-AP.bat

        Invoke-WebRequest https://drive.google.com/uc?id=1LPAWiaBYrGZ0oBeSvS_ypbhuIeAhA_dU  -OutFile NGROK-CHECK.bat

        Invoke-WebRequest https://drive.google.com/uc?id=1lo93EL_uh3Xf72DfMkHoTSbENxFN7vUa  -OutFile loop.bat

    - name: Make YML file for NGROK.

      run: start NGROK-AP.bat

    - name: Enable RDP Access.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Membuat Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 256 SSD.

      run: cmd /c start.bat

    - name: Berhasil Dibuat! Anda Bisa Menutup Tab Sekarang.

      run: cmd /c loop.bat
